# fly.toml app configuration file generated for taskflow-todo on 2026-06-23T17:15:53-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'taskflow-todo'
primary_region = 'nrt'

[build]
  [build.args]
    VITE_GOOGLE_CLIENT_ID = "826409419989-06c8u9htmrr9n496kckl1dt1fois3344.apps.googleusercontent.com"

[env]
  Authentication__Google__ClientId = "826409419989-06c8u9htmrr9n496kckl1dt1fois3344.apps.googleusercontent.com"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "taskflow_data"
  destination = "/data"
